{
 "title": "Cluster",
 "description": "This dashboard provides cluster admins with the ability to monitor nodes and identify workload bottlenecks. It can be deployed with PSPs enabled using the following helm chart - https://github.com/pivotal-cf/charts-grafana",
 "tags": [ "kubernetes" ],
 "time": { "from": "2024-01-26T10:39:13.453Z", "to": "2024-01-26T10:40:00.148Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"^^$Node$\"})"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"^^$Node$\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"^$Node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^^$Node$\"})"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage ($interval avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^^$Node$\"}[$interval])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"}) / sum (container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"^^$Node$\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"^^$Node$\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"^^$Node$\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"^^$Node$\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"^$Node\"} - node_memory_MemAvailable_bytes{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'^$Node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'^$Node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'^$Node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'^$Node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"^$Node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"^$Node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"^$Node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"^$Node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'^$Node'}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'^$Node'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'^$Node'}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'^$Node'}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'^$Node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container CPU usage total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Container memory usage total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_usage_bytes)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Container fs usage total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(instance) (container_fs_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container fs io current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "targets": [
    { "expr": "container_fs_io_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container fs read rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container fs write rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container netowrk recieve total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(instance) (container_network_receive_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container network transmit total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
   "targets": [
    {
     "expr": "sum by(instance) (container_network_transmit_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container network receive rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container network transmit rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vm_cpu_idle_rate($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cpu_idle_rate{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  },
  {
   "title": "vm_cpu_system_proc_rate$interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cpu_system_proc_rate{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  },
  {
   "title": "vm_cpu_usr_proc_rate$interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cpu_usr_proc_rate{host=~\"^$Node$\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  },
  {
   "title": "vm_disk_read_bytes_per_secend$interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_disk_read_bytes_per_secend{host=~\"^$Node\"})by(vm)",
     "legendFormat": "read-{{ vm}}"
    },
    {
     "expr": "sum(vm_disk_write_bytes_per_secend{host=~\"^$Node\",exported_host=~\"^$Node\"})by(vm)",
     "legendFormat": "write-{{ vm}}"
    }
   ]
  },
  {
   "title": "vm_disk_read/write_requests_per_secend$interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_disk_read_requests_per_secend{host=~\"^$Node\"})by(vm)",
     "legendFormat": "read-{{ vm}}"
    },
    {
     "expr": "sum(vm_disk_write_requests_per_secend{host=~\"^$Node\",exported_host=~\"^$Node\"})by(vm)",
     "legendFormat": "write-{{ vm}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_mem_total_bytes{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "vm_network_send/receive_bytes($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_network_receive_bytes_per_secend{host=\"$Node\"})by(vm)",
     "legendFormat": "-> {{ vm }}"
    },
    {
     "expr": "sum(vm_network_send_bytes_per_secend{host=~\"^$Node\",exported_host=~\"^$Node\"})by(vm)",
     "legendFormat": "<- {{ vm }}"
    }
   ]
  },
  {
   "title": "vm_network_send/receive_drops($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_network_receive_drops_per_secend{host=\"$Node\"})by(vm)",
     "legendFormat": "-> {{ vm }}"
    },
    {
     "expr": "sum(vm_network_send_drops_per_secend{host=~\"^$Node\",exported_host=~\"^$Node\"})by(vm)",
     "legendFormat": "<- {{ vm }}"
    }
   ]
  },
  {
   "title": "vm_network_send/receive_errors($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_network_receive_errors_per_secend{host=~\"$Node\"})by(vm)",
     "legendFormat": "-> {{ vm }}"
    },
    {
     "expr": "sum(vm_network_send_errors_per_secend{host=~\"^$Node\",exported_host=~\"^$Node\"})by(vm)",
     "legendFormat": "<- {{ vm }}"
    }
   ]
  },
  {
   "title": "vm_network_send/receive_packages($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_network_receive_packages_per_secend{host=~\"$Node\"})by(vm)",
     "legendFormat": "-> {{ vm }}"
    },
    {
     "expr": "sum(vm_network_send_packages_per_secend{host=~\"^$Node\",exported_host=~\"^$Node\"})by(vm)",
     "legendFormat": "<- {{ vm }}"
    }
   ]
  },
  {
   "title": "VM Memory($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_mem_total_bytes{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  },
  {
   "title": "VM available memory($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_mem_available_bytes{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  },
  {
   "title": "vm memory buffers($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vm_mem_buffers_bytes{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  },
  {
   "title": "vm_mem_rate($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vm_mem_rate{host=~\"^$Node\"})by(vm)",
     "legendFormat": "{{ vm}}"
    }
   ]
  }
 ]
}